name: "Test Catalogue 1"
description: "Specifications for all the interfaces in the across the system X."
spec-files: 
- file-path: "specs/example-template.yaml"
- repo: "pburls/specs-test2"
  file-path: "specs/example-spec.yaml"